@startuml

class HangMan
class Player
class SecretWord
class Turn
class HangedMan

interface WordGiver
interface WordGuesser
interface HangManPlayer

HangMan o-- Player
HangMan *--Turn
Turn*-- SecretWord
Turn*-- HangedMan

Player <|..HangManPlayer
HangManPlayer<|-- WordGuesser
HangManPlayer<|-- WordGiver
Turn --* Player

@enduml